# Generated by Django 5.0 on 2023-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownership',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='smartphone',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='transfer_date',
        ),
        migrations.AddField(
            model_name='ownership',
            name='IMEI_Number',
            field=models.CharField(default='000000000000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
