# Generated by Django 5.0 on 2023-12-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0002_rename_user_ownership_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
