# Generated by Django 5.0 on 2023-12-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='mobile_number',
            field=models.CharField(default='+910000000000', max_length=15),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
