# Generated by Django 5.0 on 2023-12-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0005_ownership_mobile_number_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='email',
            field=models.EmailField(default='', max_length=20, unique=True),
        ),
    ]
