# Generated by Django 5.0 on 2023-12-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0006_ownership_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
