# Generated by Django 5.0 on 2023-12-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
