# Generated by Django 5.0 on 2024-01-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0009_alter_ownership_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='transfer_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
