# Generated by Django 5.0 on 2024-01-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0010_ownership_transfer_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownership',
            name='user_profile',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='ownership_transfer.userprofile'),
        ),
    ]
