# Generated by Django 5.0 on 2024-01-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0011_ownership_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownership_transfer.userprofile'),
        ),
    ]
