# Generated by Django 5.0 on 2024-01-05 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0013_remove_ownership_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_owner', to=settings.AUTH_USER_MODEL)),
                ('old_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_owner', to=settings.AUTH_USER_MODEL)),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownership_transfer.ownership')),
            ],
        ),
    ]
