# Generated by Django 5.0 on 2024-01-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0015_alter_ownershiptransfer_new_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnershipTransfer',
        ),
    ]
