# Generated by Django 5.0 on 2024-01-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0016_delete_ownershiptransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
