# Generated by Django 5.0 on 2024-01-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership_transfer', '0019_alter_ownership_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
